/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogDetectingPromptInjectionInProductionRouteImport } from './routes/blog/detecting-prompt-injection-in-production'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogDetectingPromptInjectionInProductionRoute =
  BlogDetectingPromptInjectionInProductionRouteImport.update({
    id: '/blog/detecting-prompt-injection-in-production',
    path: '/blog/detecting-prompt-injection-in-production',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/blog/detecting-prompt-injection-in-production': typeof BlogDetectingPromptInjectionInProductionRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/blog/detecting-prompt-injection-in-production': typeof BlogDetectingPromptInjectionInProductionRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/blog/detecting-prompt-injection-in-production': typeof BlogDetectingPromptInjectionInProductionRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/docs' | '/blog/detecting-prompt-injection-in-production' | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/blog/detecting-prompt-injection-in-production' | '/blog'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/blog/detecting-prompt-injection-in-production'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  BlogDetectingPromptInjectionInProductionRoute: typeof BlogDetectingPromptInjectionInProductionRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/detecting-prompt-injection-in-production': {
      id: '/blog/detecting-prompt-injection-in-production'
      path: '/blog/detecting-prompt-injection-in-production'
      fullPath: '/blog/detecting-prompt-injection-in-production'
      preLoaderRoute: typeof BlogDetectingPromptInjectionInProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  BlogDetectingPromptInjectionInProductionRoute:
    BlogDetectingPromptInjectionInProductionRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
